parameters:
    messenger_import_dsn: "%env(MESSENGER_TRANSPORT_DSN)%/import"
    messenger_export_dsn: "%env(MESSENGER_TRANSPORT_DSN)%/export"

framework:
    messenger:
        transports:
            export:
                dsn: "%messenger_export_dsn%"
            import:
                dsn: "%messenger_import_dsn%"
        routing:
            'ReiffIntegrations\MeDaPro\Message\CategoryImportMessage': import
            'ReiffIntegrations\MeDaPro\Message\ManufacturerImportMessage': import
            'ReiffIntegrations\MeDaPro\Message\ProductImportMessage': import
            'ReiffIntegrations\MeDaPro\Message\PropertyImportMessage': import
            'ReiffIntegrations\Seeburger\Message\OrderExportMessage': export
