parameters:
    messenger_import_dsn: "%env(MESSENGER_TRANSPORT_DSN)%/import"
    messenger_export_dsn: "%env(MESSENGER_TRANSPORT_DSN)%/export"

framework:
    messenger:
        transports:
            export:
                dsn: "%messenger_export_dsn%"
            import:
                dsn: "%messenger_import_dsn%"
        routing:
            'ReiffIntegrations\MeDaPro\Message\ProductImportMessage': import
